### ISSUE TITLE
Anitya checker: ignore pre-releases

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/flatpak-external-data-checker#121]
Anitya allows filtering out pre-releases, which would make the results of the checker more accurate: https://github.com/fedora-infra/anitya/issues/898

**Comment by gasinvein** [comment]
AFAIK Anitya doesn't yet expose stable versions in it's JSON API. See fedora-infra/anitya#1014
Once it does, we'll add some `stable-only: bool` property support to AnityaChecker.

**Comment by Zlopez** [comment]
The fedora-infra/anitya#1014 is now implemented and the new version is running in production. Feel free to use this :-)
